# Generated by Django 4.1.7 on 2023-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('security', 'Agent de sécurité '), ('manager', 'Directeur'), ('secretary', 'Sécrétaire'), ('general', 'Utilisateur Général')], default='general', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
