# Generated by Django 4.1.7 on 2023-04-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='sec_level',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
