# Generated by Django 4.1.7 on 2023-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_role_sec_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fr_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sec_level', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('security', 'Agent de sécurité'), ('manager', 'Directeur'), ('secretary', 'Sécrétaire'), ('general', 'Utilisateur Général')], default='general', max_length=50, null=True),
        ),
    ]
