# Generated by Django 4.1.7 on 2023-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userrole_delete_role_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='sec_level',
            field=models.IntegerField(default='0'),
        ),
    ]
