# Generated by Django 4.1.7 on 2023-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userrole_sec_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sec_level', models.IntegerField(default='0')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='tel',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
