# Generated by Django 4.1.7 on 2023-04-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subcategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
