# Generated by Django 4.2 on 2023-05-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_service_category_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
