# Generated by Django 4.2 on 2023-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sectors'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
